server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
  rabbitmq:
    host: localhost
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true